version: "3"

services:
  couponcreator:
    build:
      context: ./
      dockerfile: Dockerfile
    environment:
      APP_ENVIRONMENT: development
      FLASK_APP: app/application.py
    depends_on:
      - mock_woocommerce
    volumes:
      - .:/app
    working_dir: /app
    ports:
      - 5000:5000

  mock_woocommerce:
    build:
      context: ./
      dockerfile: Dockerfile.mock_upstream
    environment:
      APP_ENVIRONMENT: development
      FLASK_APP: tests/mock_upstream.py
    volumes:
      - .:/app
    working_dir: /app
    ports:
      - 5001:5000